+--------+-----------+----------------------------------+---------------------------------+---------------------------------------------------------------------------------+-----------------------------------------------------------+
| Domain | Method    | URI                              | Name                            | Action                                                                          | Middleware                                                |
+--------+-----------+----------------------------------+---------------------------------+---------------------------------------------------------------------------------+-----------------------------------------------------------+
|        | GET|HEAD  | /                                |                                 | Closure                                                                         | web                                                       |
|        | POST      | admin/categories                 | admin.categories.store          | App\Http\Controllers\CategoryController@store                                   | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | GET|HEAD  | admin/categories                 | admin.categories.index          | App\Http\Controllers\CategoryController@index                                   | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | DELETE    | admin/categories/{category}      | admin.categories.destroy        | App\Http\Controllers\CategoryController@destroy                                 | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | PUT|PATCH | admin/categories/{category}      | admin.categories.update         | App\Http\Controllers\CategoryController@update                                  | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | POST      | admin/orders                     | admin.orders.store              | App\Http\Controllers\OrderController@store                                      | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | GET|HEAD  | admin/orders                     | admin.orders.index              | App\Http\Controllers\OrderController@index                                      | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | GET|HEAD  | admin/orders/create              | admin.orders.create             | App\Http\Controllers\OrderController@create                                     | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | DELETE    | admin/orders/{order}             | admin.orders.destroy            | App\Http\Controllers\OrderController@destroy                                    | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | PUT|PATCH | admin/orders/{order}             | admin.orders.update             | App\Http\Controllers\OrderController@update                                     | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | GET|HEAD  | admin/orders/{order}/edit        | admin.orders.edit               | App\Http\Controllers\OrderController@edit                                       | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | GET|HEAD  | admin/products                   | admin.products.index            | App\Http\Controllers\ProductController@index                                    | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | POST      | admin/products                   | admin.products.store            | App\Http\Controllers\ProductController@store                                    | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | GET|HEAD  | admin/products/create            | admin.products.create           | App\Http\Controllers\ProductController@create                                   | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | DELETE    | admin/products/{product}         | admin.products.destroy          | App\Http\Controllers\ProductController@destroy                                  | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | PUT|PATCH | admin/products/{product}         | admin.products.update           | App\Http\Controllers\ProductController@update                                   | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | GET|HEAD  | admin/products/{product}/edit    | admin.products.edit             | App\Http\Controllers\ProductController@edit                                     | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | GET|HEAD  | admin/transactions               | admin.transactions.index        | App\Http\Controllers\TransactionController@index                                | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | PUT|PATCH | admin/transactions/{transaction} | admin.transactions.update       | App\Http\Controllers\TransactionController@update                               | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | DELETE    | admin/transactions/{transaction} | admin.transactions.destroy      | App\Http\Controllers\TransactionController@destroy                              | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | GET|HEAD  | api/user                         |                                 | Closure                                                                         | api                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        | GET|HEAD  | dashboard                        | dashboard                       | Closure                                                                         | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate:sanctum                  |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | POST      | forgot-password                  | password.email                  | Laravel\Fortify\Http\Controllers\PasswordResetLinkController@store              | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\RedirectIfAuthenticated               |
|        | GET|HEAD  | forgot-password                  | password.request                | Laravel\Fortify\Http\Controllers\PasswordResetLinkController@create             | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\RedirectIfAuthenticated               |
|        | GET|HEAD  | livewire/livewire.js             |                                 | Livewire\Controllers\LivewireJavaScriptAssets@source                            |                                                           |
|        | GET|HEAD  | livewire/livewire.js.map         |                                 | Livewire\Controllers\LivewireJavaScriptAssets@maps                              |                                                           |
|        | POST      | livewire/message/{name}          | livewire.message                | Livewire\Controllers\HttpConnectionHandler                                      | web                                                       |
|        | GET|HEAD  | livewire/preview-file/{filename} | livewire.preview-file           | Livewire\Controllers\FilePreviewHandler@handle                                  | web                                                       |
|        | POST      | livewire/upload-file             | livewire.upload-file            | Livewire\Controllers\FileUploadHandler@handle                                   | web                                                       |
|        |           |                                  |                                 |                                                                                 | Illuminate\Routing\Middleware\ThrottleRequests:60,1       |
|        | POST      | login                            |                                 | Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@store           | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\RedirectIfAuthenticated               |
|        |           |                                  |                                 |                                                                                 | Illuminate\Routing\Middleware\ThrottleRequests:login      |
|        | GET|HEAD  | login                            | login                           | Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@create          | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\RedirectIfAuthenticated               |
|        | POST      | logout                           | logout                          | Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@destroy         | web                                                       |
|        | GET|HEAD  | privacy-policy                   | policy.show                     | Laravel\Jetstream\Http\Controllers\Livewire\PrivacyPolicyController@show        | web                                                       |
|        | GET|HEAD  | register                         | register                        | Laravel\Fortify\Http\Controllers\RegisteredUserController@create                | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\RedirectIfAuthenticated               |
|        | POST      | register                         |                                 | Laravel\Fortify\Http\Controllers\RegisteredUserController@store                 | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\RedirectIfAuthenticated               |
|        | POST      | reset-password                   | password.update                 | Laravel\Fortify\Http\Controllers\NewPasswordController@store                    | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\RedirectIfAuthenticated               |
|        | GET|HEAD  | reset-password/{token}           | password.reset                  | Laravel\Fortify\Http\Controllers\NewPasswordController@create                   | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\RedirectIfAuthenticated               |
|        | GET|HEAD  | sanctum/csrf-cookie              |                                 | Laravel\Sanctum\Http\Controllers\CsrfCookieController@show                      | web                                                       |
|        | GET|HEAD  | terms-of-service                 | terms.show                      | Laravel\Jetstream\Http\Controllers\Livewire\TermsOfServiceController@show       | web                                                       |
|        | GET|HEAD  | two-factor-challenge             | two-factor.login                | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController@create | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\RedirectIfAuthenticated               |
|        | POST      | two-factor-challenge             |                                 | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController@store  | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\RedirectIfAuthenticated               |
|        |           |                                  |                                 |                                                                                 | Illuminate\Routing\Middleware\ThrottleRequests:two-factor |
|        | GET|HEAD  | user/confirm-password            | password.confirm                | Laravel\Fortify\Http\Controllers\ConfirmablePasswordController@show             | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate                          |
|        | POST      | user/confirm-password            |                                 | Laravel\Fortify\Http\Controllers\ConfirmablePasswordController@store            | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate                          |
|        | GET|HEAD  | user/confirmed-password-status   | password.confirmation           | Laravel\Fortify\Http\Controllers\ConfirmedPasswordStatusController@show         | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate                          |
|        | PUT       | user/password                    | user-password.update            | Laravel\Fortify\Http\Controllers\PasswordController@update                      | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate                          |
|        | GET|HEAD  | user/profile                     | profile.show                    | Laravel\Jetstream\Http\Controllers\Livewire\UserProfileController@show          | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate                          |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\EnsureEmailIsVerified          |
|        | PUT       | user/profile-information         | user-profile-information.update | Laravel\Fortify\Http\Controllers\ProfileInformationController@update            | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate                          |
|        | POST      | user/two-factor-authentication   |                                 | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController@store        | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate                          |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\RequirePassword                |
|        | DELETE    | user/two-factor-authentication   |                                 | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController@destroy      | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate                          |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\RequirePassword                |
|        | GET|HEAD  | user/two-factor-qr-code          |                                 | Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController@show                 | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate                          |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\RequirePassword                |
|        | GET|HEAD  | user/two-factor-recovery-codes   |                                 | Laravel\Fortify\Http\Controllers\RecoveryCodeController@index                   | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate                          |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\RequirePassword                |
|        | POST      | user/two-factor-recovery-codes   |                                 | Laravel\Fortify\Http\Controllers\RecoveryCodeController@store                   | web                                                       |
|        |           |                                  |                                 |                                                                                 | App\Http\Middleware\Authenticate                          |
|        |           |                                  |                                 |                                                                                 | Illuminate\Auth\Middleware\RequirePassword                |
+--------+-----------+----------------------------------+---------------------------------+---------------------------------------------------------------------------------+-----------------------------------------------------------+
